version: "3.9"

services:
  redis:
    image: redis
    restart: always

  support:
    restart: always
    build:
      context: ./support
    ports:
      - "8000:8000"
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]