version: "3.9"

services:
  redis:
    image: redis
    restart: always

  support:
    restart: always
    build:
      context: ./support
    ports:
      - "8000:8000"
    command: ["./support_run.bash"]
    depends_on:
      db:
        condition: service_healthy

  worker:
    restart: always
    build:
      context: ./support
    command: ["celery", "--workdir=./src", "-A", "support", "worker"]
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres
    ports:
      - '5432'
    volumes: 
      - ./support/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5