# Generated by Django 3.2.8 on 2021-10-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_change_status', 'Can change status'), ('can_message_in_different_ticket', 'Can send message in different ticket')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
