# Generated by Django 3.2.8 on 2021-10-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_view_all_tickets', 'Can view all tickets'), ('can_change_status', 'Can change status'), ('can_message_in_different_tickets', 'Can send message in different tickets')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
